version: '3'
services:
  app_python:
    image: dapp7anyway/devops:latest
    build: app_python
    volumes:
      - volume-python:/app/volume
    expose:
      - 4000
    ports:
      - 4000:4000

volumes:
  volume-python: