apiVersion: v1
kind: Service
metadata:
  name: devops-server-service
spec:
  selector:
    app: devops-server
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 4000
      targetPort: 4000
  